package main.java.game.model;


public class Currencies {
	protected int currency_id;
	protected String currency_name ;
	protected double max_cap;
	protected double weekly_cap;
	protected double amount;
	protected double amount_weekly;
	
	// This constructor can be used for reading records from MySQL, where we have all fields,
	// including the currency_id.
	public Currencies(int currency_id, String currency_name, double max_cap, double weekly_cap, double amount,
			double amount_weekly) {
		this.currency_id = currency_id;
		this.currency_name = currency_name;
		this.max_cap = max_cap;
		this.weekly_cap = weekly_cap;
		this.amount = amount;
		this.amount_weekly = amount_weekly;
	}
	
	public Currencies(int currency_id, double amount, double amount_weekly) {
		this.currency_id = currency_id;
		this.amount = amount;
		this.amount_weekly = amount_weekly;
	}
	
	// This constructor can be used for reading records from MySQL, where we only have the currency_id,
	// such as a foreign key reference to currency_id.
	// Given currency_id, we can fetch the full Currencies record.
	public Currencies(int currency_id) {
		this.currency_id = currency_id;
	}	

	// This constructor can be used for creating new records, where the currency_id may not be
	// assigned yet since it is auto-generated by MySQL.
	public Currencies(String currency_name, double max_cap, double weekly_cap, double amount, double amount_weekly) {
		super();
		this.currency_name = currency_name;
		this.max_cap = max_cap;
		this.weekly_cap = weekly_cap;
		this.amount = amount;
		this.amount_weekly = amount_weekly;
	}
	
	/** Getters and setters. */

	public int getCurrency_id() {
		return currency_id;
	}

	public void setCurrency_id(int currency_id) {
		this.currency_id = currency_id;
	}

	public String getCurrency_name() {
		return currency_name;
	}

	public void setCurrency_name(String currency_name) {
		this.currency_name = currency_name;
	}

	public double getMax_cap() {
		return max_cap;
	}

	public void setMax_cap(double max_cap) {
		this.max_cap = max_cap;
	}

	public double getWeekly_cap() {
		return weekly_cap;
	}

	public void setWeekly_cap(double weekly_cap) {
		this.weekly_cap = weekly_cap;
	}

	public double getAmount() {
		return amount;
	}

	public void setAmount(double amount) {
		this.amount = amount;
	}

	public double getAmount_weekly() {
		return amount_weekly;
	}

	public void setAmount_weekly(double amount_weekly) {
		this.amount_weekly = amount_weekly;
	}

}